# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: wyyder/jenkins-customised:latest
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: wyyder-jenkins
    volumes:
      # Enable persistent volume 
      # Create jenkins_home in home directory
      - ~/jenkins_home:/var/jenkins_home
      # mount docker sock and binary for docker in docker (only works on linux)
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker